/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as AuthentificatedImport } from './routes/_authentificated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthentificatedProfileImport } from './routes/_authentificated/profile'
import { Route as AuthentificatedExpensesImport } from './routes/_authentificated/expenses'
import { Route as AuthentificatedCreateexpenseImport } from './routes/_authentificated/create_expense'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const AuthentificatedRoute = AuthentificatedImport.update({
  id: '/_authentificated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthentificatedProfileRoute = AuthentificatedProfileImport.update({
  path: '/profile',
  getParentRoute: () => AuthentificatedRoute,
} as any)

const AuthentificatedExpensesRoute = AuthentificatedExpensesImport.update({
  path: '/expenses',
  getParentRoute: () => AuthentificatedRoute,
} as any)

const AuthentificatedCreateexpenseRoute =
  AuthentificatedCreateexpenseImport.update({
    path: '/create_expense',
    getParentRoute: () => AuthentificatedRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authentificated': {
      id: '/_authentificated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthentificatedImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/_authentificated/create_expense': {
      id: '/_authentificated/create_expense'
      path: '/create_expense'
      fullPath: '/create_expense'
      preLoaderRoute: typeof AuthentificatedCreateexpenseImport
      parentRoute: typeof AuthentificatedImport
    }
    '/_authentificated/expenses': {
      id: '/_authentificated/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof AuthentificatedExpensesImport
      parentRoute: typeof AuthentificatedImport
    }
    '/_authentificated/profile': {
      id: '/_authentificated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthentificatedProfileImport
      parentRoute: typeof AuthentificatedImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthentificatedRoute: AuthentificatedRoute.addChildren({
    AuthentificatedCreateexpenseRoute,
    AuthentificatedExpensesRoute,
    AuthentificatedProfileRoute,
  }),
  AboutRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authentificated",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authentificated": {
      "filePath": "_authentificated.tsx",
      "children": [
        "/_authentificated/create_expense",
        "/_authentificated/expenses",
        "/_authentificated/profile"
      ]
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/_authentificated/create_expense": {
      "filePath": "_authentificated/create_expense.tsx",
      "parent": "/_authentificated"
    },
    "/_authentificated/expenses": {
      "filePath": "_authentificated/expenses.tsx",
      "parent": "/_authentificated"
    },
    "/_authentificated/profile": {
      "filePath": "_authentificated/profile.tsx",
      "parent": "/_authentificated"
    }
  }
}
ROUTE_MANIFEST_END */
